experiment:
  name: "BRANCHING"
  description: "Neuronal/Dendritic network with continuous branching paths."

physics:
  wavelength_um: 0.635
  probe_dia_um: 10.0
  probe_focus_um: 0.0

grid:
  n_physical: 1024
  n_padding: 256
  physical_width_um: 150.0

sample:
  type: "BRANCHING"
  thickness_um: 200.0

  # Ground Truth Settings (Reference Solution)
  ground_truth:
    n_prop_fine: 2000      # High-res propagation steps for reference
    solver_type: "PADE"    # Which algorithm to trust as "truth"
    solver_params:
      pade_order: 8       # Very high accuracy for reference

    save_file: "./data/branching_gt_ref.npz"

  params:
    n_background: 1.00
    delta_n: 0.04
    initial_thickness: 7.0
    branching_prob: 0.006
    split_angle: 0.20
    repulsion: 0.005

# Benchmarking List
# List as many solvers as desired for comparison
solvers:
  - name: "Pade (Order 8)" # Arbitrary Name
    type: "PADE"
    solver_params:
      pade_order: 8

  - name: "Multislice (DST)"
    type: "MULTISLICE"
    solver_params:
      transform_type: "DST"
      symmetric: false

benchmark:
  step_counts: [16, 32,64, 128, 256]
  save_beam_idx: 0
